# Generated by Django 5.1.1 on 2024-10-01 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productentry_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productentry',
            name='time',
        ),
    ]
