# Generated by Django 5.1.1 on 2024-10-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_productentry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentry',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
